version: 1.0
provider:
  name: openfaas
  gateway: https://cellerich.fimocello.dev/function
functions:
  goto:
    lang: node10-express
    handler: ./goto
    image: cellerich/goto:latest
    
    
    
