version: 1.0
provider:
  name: openfaas
  gateway: https://cellerich.cloudfunction.ch/function
functions:
  goto:
    lang: node10-express
    handler: ./goto
    image: cloudfunction/goto:latest
    
    
    
